import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  jest: false,
  workspaces: {
    'apps/mumak-next': {
      entry: ['app/**/*.{ts,tsx}', 'components/**/*.{ts,tsx}', 'next.config.mjs', 'postcss.config.mjs'],
      project: ['**/*.{ts,tsx}'],
      ignore: [
        '.next/**',
        'out/**',
        'node_modules/**',
        '**/*.test.{ts,tsx}',
        '**/*.spec.{ts,tsx}',
        '__tests__/**',
        'e2e/**',
        'jest.config.*',
        'jest.setup.*',
        'playwright.config.*',
      ],
      ignoreDependencies: [
        '@playwright/test',
        '@testing-library/jest-dom',
        '@testing-library/react',
        '@testing-library/user-event',
        '@types/jest',
        'jest',
        'jest-environment-jsdom',
      ],
    },
    'apps/mumak-react': {
      entry: ['src/**/*.{ts,tsx}', 'index.html', 'vite.config.ts', 'vitest.config.js'],
      project: ['**/*.{ts,tsx}'],
      ignore: [
        'dist/**',
        'node_modules/**',
        '**/*.test.{ts,tsx}',
        '**/*.spec.{ts,tsx}',
        '__tests__/**',
        'e2e/**',
        'playwright.config.*',
      ],
      ignoreDependencies: [
        '@playwright/test',
        '@testing-library/jest-dom',
        '@testing-library/react',
        '@testing-library/user-event',
        '@vitest/coverage-v8',
        '@vitest/ui',
        'jsdom',
        'vitest',
      ],
    },
    'packages/ui': {
      entry: ['src/**/*.{ts,tsx}', 'postcss.config.mjs'],
      project: ['**/*.{ts,tsx}'],
      ignore: ['node_modules/**', 'dist/**', '**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}'],
    },
    'packages/typescript-config': {
      entry: ['**/*.json'],
      project: ['**/*.json'],
      ignore: ['node_modules/**'],
    },
  },
  ignore: [
    '**/node_modules/**',
    '**/.next/**',
    '**/out/**',
    '**/dist/**',
    '**/.turbo/**',
    '**/coverage/**',
    '**/test-results/**',
    '**/playwright-report/**',
    '**/*.tsbuildinfo',
    '**/pnpm-lock.yaml',
    '**/.env*',
  ],
  ignoreDependencies: [
    '@playwright/test',
    '@testing-library/jest-dom',
    '@testing-library/react',
    '@testing-library/user-event',
    '@types/jest',
    '@types/node',
    '@types/react',
    '@types/react-dom',
    '@vitest/coverage-v8',
    '@vitest/ui',
    'jest',
    'jest-environment-jsdom',
    'jsdom',
    'postcss',
    'postcss-load-config',
    'typescript',
    'vitest',
  ],
};

export default config;
